<?php

    echo $this->escapeHtml( $this->getMethod()->getTitle() ).'{{pdf_row_separator}}';

    if( ($_specificInfo = $this->getSpecificInformation()) )
    {
        foreach ($_specificInfo as $_label => $_value)
        {
            echo $this->__( $_label ).'{{pdf_row_separator}}';
            echo nl2br( implode( $this->getValueAsArray( $_value, true ), "{{pdf_row_separator}}\n" ) ).'{{pdf_row_separator}}';
        }
    }

    echo $this->getChildHtml();

