<?php
    /** @var Smart2Pay_Globalpay_Block_Info_Globalpay $this */
?>
<p><?php echo $this->escapeHtml( $this->getMethod()->getTitle() ) ?></p>

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<table>
    <tbody>
    <?php foreach ($_specificInfo as $_label => $_value):?>
        <tr>
            <td class="label"><label><em><?php echo $this->__( $_label )?></em></label></td>
            <?php
            if( empty( $this->_display_lines ) )
            {
                ?></tr><tr><?php
            }
            ?>
            <td class="value"><?php echo nl2br(implode($this->getValueAsArray($_value, true), "\n"))?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif;?>

<?php echo $this->getChildHtml()?>
