<div style="clear:both;"></div>
<?php
/** @var Smart2Pay_Globalpay_Block_Paymethod_Form $this */
$_code = $this->getMethodCode();
$s2pMethods = $this->getPaymentMethods();
?>

<style type="text/css">
.s2p-method-wrapper { display: block; white-space: nowrap; float: left; }
.s2p-method-name { display: block; float: left; }
.s2p-method-img { float: left; vertical-align: middle; max-height:40px; max-width:130px; }
a .s2p-method-img, a .s2p-method-name, a .s2p-method-img-name, .s2p-method-ck { cursor: pointer; float: left; }
.s2p-method-ck { margin-top: 10px; max-width: 30px; }
.s2p-method-img-wrapper { min-height: 40px; vertical-align: middle; padding-left: 30px; }

#payment_form_globalpay { background-color: #F3F3F3; border: 1px solid #CCC; border-left: 2px solid #CCC; }

<?php
if( !$this->method_config['show_methods_in_grid'] )
{
?>
#payment_form_globalpay td { padding: 10px; }
.s2p-method-img-name.no-grid-w-description-title {
    border-bottom: 1px solid #CCCCCC;
    font-size: 100%;
    font-weight: bold;
    margin-bottom: 2px;
    padding-bottom: 2px;
}
.s2p-method-img-name.no-grid-w-description-content { font-size: 80%; }
<?php
} elseif( $this->method_config['grid_column_number'] == 1 )
{
?>
.grid.one-column { text-align: left; padding: 15px; }
.s2p-method-img-name { padding: 5px 0px 0px 26px; }
<?php
} else
{
?>
.grid.one-column { padding: 15px; }
.s2p-method-img-name { padding: 5px 0px 0px 26px; }
<?php
}
?>

.s2p-method-img-name { display: block; /*float: right;*/ }
.s2p-method-img { padding-left: 15px; }
</style>

<input type="hidden" id="s2p-payment-method" name="payment[method_id]" value="0" />
<div id="payment_form_globalpay" style="display: none;">
<?php
    /*
     * Send payment method
     */
    if( empty( $s2pMethods ) or !is_array( $s2pMethods ) )
    {
        ?><p style="text-align: center; padding: 5px;"><?php

        echo $this->__( 'No methods found for current settings.' );

        if( is_string( $s2pMethods ) )
            echo '<br/>'.$s2pMethods;

        ?></p><?php
    } elseif( !empty( $s2pMethods ) and is_array( $s2pMethods ) )
    {
        $s2pMethods_count = count( $s2pMethods );
        ?>
        <table style="width: 100%;">
        <?php
        /*
         * Show methods in grid
         */
        if( $this->method_config['show_methods_in_grid'] )
        {
            //show methods in grid
            $grid_col_number = ((int)$this->method_config['grid_column_number'] > 0) ? (int)$this->method_config['grid_column_number'] : 3;
            $printed_grid_cols = 0;
            while( $printed_grid_cols < $s2pMethods_count )
            {
                ?><tr><?php

                for( $c = 0; $c < $grid_col_number; $c++ )
                {
                    if( isset( $s2pMethods[$printed_grid_cols] ) )
                    {
                        $method = $s2pMethods[$printed_grid_cols];

                        ?>
                        <td class="grid one-column"><label class="s2p-method-wrapper" style="width: 100%;">
                            <input type="radio" class="s2p-method-ck <?php echo (($printed_grid_cols == 0)?'s2p-first-method-ck':'')?>" id="s2p-method-chck-<?php echo $method['method_id'] ?>" value="<?php echo $method['method_id']?>" />
                            <div class="s2p-method-img-wrapper">
                            <?php

                            $surcharge_explained_str = '';
                            if( (int)$this->method_config['display_surcharge']
                            and ((float)$method['surcharge'] != 0 or (float)$method['fixed_amount'] != 0) )
                            {
                                $surcharge_explained_str = '<div style="clear: both;"></div>(';

                                if( (float)$method['surcharge'] != 0 )
                                    $surcharge_explained_str .= ( $method['surcharge'] > 0 ? '+' : '' ) . $method['surcharge'] . '%';
                                if( (float)$method['fixed_amount'] != 0 )
                                    $surcharge_explained_str .= ((float)$method['surcharge'] != 0?' + ':'').
                                                Mage::getSingleton('checkout/session')->getQuote()->getStore()->getBaseCurrency()->format( $method['fixed_amount'], array(), false );

                                $surcharge_explained_str .= ')';
                            }

                            if( $this->method_config['methods_display_mode'] == 'text' )
                            {
                                ?><span class="s2p-method-img-name"><?php echo $this->__( $method['display_name'] ).$surcharge_explained_str?></span><?php
                            } elseif( $this->method_config['methods_display_mode'] == 'logo' )
                            {
                                ?>
                                <img class="s2p-method-img" alt="<?php echo $this->__( $method['display_name'] ); ?>" src='<?php echo $this->getSkinUrl( 'images/smart2pay/methods/'.$method['logo_url'] ); ?>' />
                                <?php
                                echo $surcharge_explained_str;
                            } else
                            {
                                ?>
                                <img class="s2p-method-img" alt="<?php echo $this->__( $method['display_name'] ); ?>" src='<?php echo $this->getSkinUrl( 'images/smart2pay/methods/'.$method['logo_url'] ); ?>' />
                                <div style="clear: both;"></div>
                                <span class="s2p-method-img-name"><?php echo $this->__( $method['display_name'] ).$surcharge_explained_str; ?></span><?php
                            }
                            ?></div></label></td><?php
                    } else
                    {
                        ?><td></td><?php
                    }

                    $printed_grid_cols++;
                }

                ?></tr><?php
            }
            /*
             * Show methods in 2 column table
             */
        } else
        {
            $k = 0;
            foreach( $s2pMethods as $key => $method )
            {
                ?>
                <tr>
                    <td style='vertical-align: middle;'><label class="s2p-method-wrapper" style="width: 100%;" for="s2p-method-chck-<?php echo $method['method_id']?>">
                        <input type="radio" class="s2p-method-ck <?php echo (($k == 0)?'s2p-first-method-ck':'')?>" id="s2p-method-chck-<?php echo $method['method_id']?>" value="<?php echo $method['method_id']?>" />
                        <div class="s2p-method-img-wrapper">
                        <?php

                        $surcharge_explained_str = '';
                        if( (int)$this->method_config['display_surcharge']
                        and ((float)$method['surcharge'] != 0 or (float)$method['fixed_amount'] != 0) )
                        {
                            $surcharge_explained_str = ' (';

                            if( (float)$method['surcharge'] != 0 )
                                $surcharge_explained_str .= ( $method['surcharge'] > 0 ? '+' : '' ) . $method['surcharge'] . '%';
                            if( (float)$method['fixed_amount'] != 0 )
                                $surcharge_explained_str .= ((float)$method['surcharge'] != 0?' + ':'').
                                                            Mage::getSingleton('checkout/session')->getQuote()->getStore()->getBaseCurrency()->format( $method['fixed_amount'], array(), false );

                            $surcharge_explained_str .= ')';
                        }

                        if( $this->method_config['methods_display_mode'] == 'text' )
                        {
                            ?><span class="s2p-method-name">&raquo <?php echo $this->__( $method['display_name'] ); ?></span><?php
                        } elseif( $this->method_config['methods_display_mode'] == 'logo' )
                        {
                            ?>
                            <img class="s2p-method-img" alt="<?php echo $this->__( $method['display_name'] ); ?>" src='<?php echo $this->getSkinUrl( 'images/smart2pay/methods/'.$method['logo_url'] ) ?>' />
                            <?php
                        } else
                        {
                            ?>
                            <img class="s2p-method-img" alt="<?php echo $this->__( $method['display_name'] ); ?>" src='<?php echo $this->getSkinUrl( 'images/smart2pay/methods/'.$method['logo_url'] ) ?>' />
                            <?php
                        }
                        ?>
                    </div></label></td>
                    <td style='padding-bottom: 10px; padding-left: 10px;'>
                        <div class="s2p-method-img-name no-grid-w-description-title">
                        <?php
                            echo $this->__( $method['display_name'] ) . $surcharge_explained_str;
                        ?>
                        </div>
                        <div class="s2p-method-img-name no-grid-w-description-content"><?php echo $this->__( $method['description'] ); ?></div>
                    </td>
                </tr>
                <?php

                $k++;
            }
        }
        ?></table><?php
    }
    ?>
</div>

<script type="text/javascript">
    jQuery.noConflict();

    function s2pChooseMethod( methodId )
    {
        var method_id_obj = jQuery('#s2p-payment-method');

        if( !method_id_obj )
            return;

        var old_method_id = method_id_obj.val();

        method_id_obj.removeAttr('disabled');
        method_id_obj.val( methodId );

        if( old_method_id )
            checkS2PMethod( old_method_id, false );
        checkS2PMethod( methodId, true );

        if( typeof payment.save == "function" )
        {
            // uncomment if you want to submit payment choice on radiobox checking event
            //payment.save();
        }
    }

    function checkS2PMethod( methodId, checked )
    {
        var chck_obj = jQuery('#s2p-method-chck-' + methodId );

        if( !chck_obj )
            return;

        chck_obj.prop( 'checked', (checked ? true : false ) );
    }

    function enableHiddenS2PField()
    {
        jQuery('#s2p-payment-method').removeAttr('disabled');
    }

    jQuery(document).ready(function()
    {
        if( jQuery().on ) {
            jQuery('.s2p-method-ck').on('click', function (e) {
                s2pChooseMethod(jQuery(this).val());
            });
        } else
        {
            jQuery('.s2p-method-ck').live( 'click', function (e) {
                s2pChooseMethod(jQuery(this).val());
            });
        }

        <?php
        if( empty( $s2pMethods ) )
        {
            ?>
            jQuery('#p_method_globalpay').parent().hide();
            jQuery('#s2p-payment-method').parent().hide();
            <?php
        } else
        {
            if( $this->method_config['autoselect_s2p']
            and !empty( $s2pMethods ) )
            {
                ?>
                jQuery('#p_method_globalpay').click();
                <?php
            }
            ?>
            jQuery('.s2p-first-method-ck').click();
            <?php
        }
        ?>
    });

    setTimeout( enableHiddenS2PField, 100 );
</script>
