<?php
    if( !empty( $this->displayPaymentInstructions ) )
    {
?>
<style type="text/css">
#BankTransferInfo { margin: 0 auto; }
#BankTransferInfo tr { text-align: left; }
#BankTransferInfo td { width: 250px; text-align: left; }
#BankTransferMessage { text-align: left; }
#BankTransferTerms { text-align: left; font-weight: bold; }
#PaymentDetails { background-color: #eeeeee; padding: 5px; }
</style>

<div id="PaymentDetails">
<p id="BankTransferMessage"><?php echo $this->__('BankTransferMessage');?></p>
<br/>
<p id="BankTransferTerms"><?php echo $this->__('BankTransferTerms');?></p>
<br/><br/>
<table id="BankTransferInfo">
<?php
    if( isset( $this->referenceNumber ) )
    {
    ?>
    <tr>
        <td><?php echo $this->__('ReferenceNumber');?></td>
        <td><?php echo $this->referenceNumber;?></td>
    </tr>
    <?php
    }

    if( isset( $this->entityNumber ) )
    {
    ?>
    <tr>
        <td><?php echo $this->__('EntityNumber');?></td>
        <td><?php echo $this->entityNumber;?></td>
    </tr>
    <?php
    }

    if( isset( $this->bankName ) )
    {
    ?>
    <tr>
        <td><?php echo $this->__('BankName');?></td>
        <td><?php echo $this->bankName;?></td>
    </tr>
    <?php
    }

    if( isset( $this->accountHolder ) )
    {
    ?>
    <tr>
        <td><?php echo $this->__('AccountHolder');?></td>
        <td><?php echo $this->accountHolder;?></td>
    </tr>
    <?php
    }

    if( isset( $this->accountNumber ) )
    {
        ?>
        <tr>
            <td><?php echo $this->__( 'AccountNumber' );?></td>
            <td><?php echo $this->accountNumber;?></td>
        </tr>
    <?php
    }

    if( isset( $this->SWIFT_BIC ) )
    {
        ?>
        <tr>
            <td><?php echo $this->__('SWIFT_BIC');?></td>
            <td><?php echo $this->SWIFT_BIC;?></td>
        </tr>
        <?php
    }

    if( isset( $this->IBAN ) )
    {
        ?>
        <tr>
            <td><?php echo $this->__('IBAN');?></td>
            <td><?php echo $this->IBAN;?></td>
        </tr>
        <?php
    }

    if( isset( $this->amountToPay ) )
    {
        ?>
        <tr>
            <td><?php echo $this->__('AmountToPay');?></td>
            <td><?php echo $this->amountToPay;?></td>
        </tr>
        <?php
    }

    if( isset( $this->accountCurrency ) )
    {
        ?>
        <tr>
            <td><?php echo $this->__( 'AccountCurrency' );?></td>
            <td><?php echo $this->accountCurrency;?></td>
        </tr>
        <?php
    }
?>
</table>
</div>
<?php
    }
    