<?php
    /** @var Smart2Pay_Globalpay_Block_Paymentinstructions $this */
    if( !empty( $this->display_params ) )
    {
?>
<style type="text/css">
#BankTransferInfo { margin: 0 auto; }
#BankTransferInfo tr { text-align: left; }
#BankTransferInfo td { width: 250px; text-align: left; }
#BankTransferMessage { text-align: left; }
#BankTransferTerms { text-align: left; font-weight: bold; }
#PaymentDetails { background-color: #eeeeee; padding: 5px; }
</style>

<div id="PaymentDetails">
<p id="BankTransferMessage"><?php echo $this->__('BankTransferMessage');?></p>
<br/>
<p id="BankTransferTerms"><?php echo $this->__('BankTransferTerms');?></p>
<br/><br/>
<table id="BankTransferInfo">
<?php
    foreach( $this->display_params as $key => $val )
    {
        ?>
        <tr>
            <td><?php echo $this->__( $key )?></td>
            <td><?php echo $val?></td>
        </tr>
        <?php

    }
?>
</table>
</div>
<?php
    }
