<?php
    /** @var Smart2Pay_Globalpay_Block_Adminhtml_System_Config_Configuredmethods $this */
?>
<input type="hidden" value="1" name="groups[selected_methods][fields][using_methods][value]" id="payment_selected_methods_using_methods" />
<style type="text/css">
.s2p-method-img-td { height:50px; width: 134px; text-align: center; }
.s2p-method-img { vertical-align: middle; max-height:40px; max-width:130px; }
.sp2-middle-all { text-align: center; vertical-align: middle; }
#s2p_methods_table  { min-width: 450px; width: 100%; margin: 0; padding: 0; }
#s2p_methods_table th { padding: 2px; text-align: center; font-weight: bold; background-color: #b6b6b6; color: black; }
#s2p_methods_table td { padding: 2px; border-bottom: 1px solid black !important; }
.s2p_methods_last_cell { border-right: 1px solid black; }
</style>
<script type="text/javascript">
function s2p_config_js_select_all()
{
    var form_obj = document.getElementById( 'config_edit_form' );
    if( !form_obj || !form_obj.elements || !form_obj.elements.length )
        return;

    for( var i = 0; i < form_obj.elements.length; i++ )
    {
        if( form_obj.elements[i].type != 'checkbox'
         || form_obj.elements[i].name != 's2p_enabled_methods[]'
         || form_obj.elements[i].checked )
            continue;

        form_obj.elements[i].checked = true;
    }
}
function s2p_config_js_deselect_all()
{
    var form_obj = document.getElementById( 'config_edit_form' );
    if( !form_obj || !form_obj.elements || !form_obj.elements.length )
        return;

    for( var i = 0; i < form_obj.elements.length; i++ )
    {
        if( form_obj.elements[i].type != 'checkbox'
         || form_obj.elements[i].name != 's2p_enabled_methods[]'
         || !form_obj.elements[i].checked )
            continue;

        form_obj.elements[i].checked = false;
    }
}
function s2p_config_js_invert()
{
    var form_obj = document.getElementById( 'config_edit_form' );
    if( !form_obj || !form_obj.elements || !form_obj.elements.length )
        return;

    for( var i = 0; i < form_obj.elements.length; i++ )
    {
        if( form_obj.elements[i].type != 'checkbox'
         || form_obj.elements[i].name != 's2p_enabled_methods[]' )
            continue;

        if( form_obj.elements[i].checked )
            form_obj.elements[i].checked = false;
        else
            form_obj.elements[i].checked = true;
    }
}
function show_all_countries_for_method( method_id, action )
{
    if( typeof action === 'undefined' )
        action = 'noforce';

    var div_obj = document.getElementById( 's2p_meth_countries_' + method_id );
    if( div_obj == null )
        return;

    if( (action == 'show' || div_obj.style.height == '40px')
        && action != 'hide' )
    {
        div_obj.style.overflow = 'visible';
        div_obj.style.height = 'auto';
    } else if( action == 'hide' || action == 'noforce' )
    {
        div_obj.style.overflow = 'hidden';
        div_obj.style.height = '40px';
    }
}
function show_all_country_custom_settings( method_id, action )
{
    if( typeof action === 'undefined' )
        action = 'toggle';

    var div_obj = document.getElementById( 's2p_meth_countries_settings_' + method_id );
    if( div_obj == null )
        return;

    //check_method_change( method_id );

    if( (action == 'toggle' && div_obj.style.display == 'none')
     || action == 'show' )
    {
        div_obj.style.display = 'block';
    } else if( (action == 'toggle' && div_obj.style.display == 'block')
            || action == 'hide' )
    {
        div_obj.style.display = 'none';
    }
}
function check_method_change( method_id )
{
    var checkbox_obj = document.getElementById( 's2p_enabled_method_' + method_id );
    if( checkbox_obj == null
     || checkbox_obj.type != "checkbox" )
        return;

    if( checkbox_obj.checked )
    {
        toggle_country_customization_for_method( method_id, "update", true );
    } else
    {
        toggle_country_customization_for_method( method_id, "disable", true );
    }
}
function toggle_country_custom_settings( method_id, action )
{
    if( typeof action === "undefined" )
        action = "toggle";

    var rex = new RegExp( "s2p_per_country\\[" + method_id + "\\]\\[[0-9]+\\]\\[[0-9a-z_\\-]+\\]" );

    var form_obj = document.getElementById( 'config_edit_form' );
    if( form_obj == null )
        return;

    if( form_obj && form_obj.elements && form_obj.elements.length )
    {
        for( var i = 0; i < form_obj.elements.length; i++ )
        {
            if( !rex.test( form_obj.elements[i].name ) )
                continue;

            if( (action == "toggle" && !form_obj.elements[i].readOnly)
             || action == "disable" )
                form_obj.elements[i].readOnly = true;

            else if( (action == "toggle" && form_obj.elements[i].readOnly)
                  || action == "enable" )
                form_obj.elements[i].readOnly = false;
        }
    }
}
function toggle_country_customization_for_method( method_id, action, include_custom_checkbox )
{
    if( typeof action === "undefined" )
        action = "update";

    if( typeof include_custom_checkbox === "undefined" )
        include_custom_checkbox = false;

    var custom_checkbox = new RegExp( "s2p_per_country\\[" + method_id + "\\]\\[([0-9]+)\\]\\[is_custom\\]" );

    var form_obj = document.getElementById( 'config_edit_form' );
    if( !form_obj || !form_obj.elements || !form_obj.elements.length )
        return;

    var country_action = "";
    for( var i = 0; i < form_obj.elements.length; i++ )
    {
        var match = form_obj.elements[i].name.match( custom_checkbox );
        if( !match
         || typeof match[1] === "undefined" )
            continue;

        if( include_custom_checkbox )
        {
            if( action == "enable" || action == "update" )
                form_obj.elements[i].disabled = false;

            else if( action == "disable" )
                form_obj.elements[i].disabled = true;
        }

        if( action == "update" )
        {
            if( form_obj.elements[i].checked )
                country_action = "enable";
            else
                country_action = "disable";
        } else
            country_action = action;

        toggle_country_customization_for_method_and_country( method_id, match[1], country_action );
    }
}
function toggle_country_customization_for_method_and_country( method_id, country_id, action )
{
    if( typeof action === "undefined" )
        action = "update";

    if( action == "update" )
    {
        var custom_obj = document.getElementById( 's2p_per_country_' + method_id + '_' + country_id + '_is_custom' );
        if( custom_obj )
        {
            if( custom_obj.checked )
                action = "enable";
            else
                action = "disable";
        }
    }
    var disabled_obj = document.getElementById( 's2p_per_country_' + method_id + '_' + country_id + '_disabled' );
    if( disabled_obj )
    {
        if( action == "disable" )
            disabled_obj.disabled = true;

        else if( action == "enable" )
        {
            if( disabled_obj.checked )
                action = "disable";

            disabled_obj.disabled = false;
        }
    }

    var my_fields = [ "surcharge", "fixed_amount", "3dsecure" ];
    for( var i = 0; i < my_fields.length; i++ )
    {
        var field_obj = document.getElementById( 's2p_per_country_' + method_id + '_' + country_id + '_' + my_fields[i] );
        if( !field_obj )
            continue;

        if( action == "enable" )
            field_obj.disabled = false;

        else if( action == "disable" )
            field_obj.disabled = true;
    }
}
function toggle_country_custom_settings_disabled( method_id, action )
{
    if( typeof action === "undefined" )
        action = "toggle";

    var rex = new RegExp( "s2p_per_country\\[" + method_id + "\\]\\[[0-9]+\\]\\[disabled\\]" );

    var form_obj = document.getElementById( 'config_edit_form' );
    if( form_obj == null )
        return;

    if( form_obj && form_obj.elements && form_obj.elements.length )
    {
        for( var i = 0; i < form_obj.elements.length; i++ )
        {
            if( !rex.test( form_obj.elements[i].name ) )
                continue;

            if( (action == "toggle" && !form_obj.elements[i].checked)
             || action == "checked" )
                form_obj.elements[i].checked = true;

            else if( (action == "toggle" && form_obj.elements[i].checked)
                  || action == "unchecked" )
                form_obj.elements[i].checked = false;
        }
    }
}
function toggle_country_custom_settings_3dsecure( method_id, action )
{
    if( typeof action === "undefined" )
        action = "default";

    var rex = new RegExp( "s2p_per_country\\[" + method_id + "\\]\\[[0-9]+\\]\\[3dsecure\\]" );

    var form_obj = document.getElementById( 'config_edit_form' );
    if( form_obj == null )
        return;

    if( form_obj && form_obj.elements && form_obj.elements.length )
    {
        for( var i = 0; i < form_obj.elements.length; i++ )
        {
            if( !rex.test( form_obj.elements[i].name ) )
                continue;

            if( action == "default" )
                form_obj.elements[i].selectedIndex = 0;

            else if( action == "yes" )
                form_obj.elements[i].selectedIndex = 1;

            else if( action == "no" )
                form_obj.elements[i].selectedIndex = 2;
        }
    }
}
</script>
<?php
    if( !($all_methods = $this->get_all_methods()) )
        $all_methods = array();
    if( !($all_configured_methods = $this->get_all_configured_methods()) )
        $all_configured_methods = array();

    /** @var Smart2Pay_Globalpay_Model_Pay $payment_model */
    if( !($payment_model = $this->get_payment_model()) )
        $payment_model = false;

    $environment = $this->get_environment();
    if( !($last_sync_date = $this->get_last_sync_date()) )
        $last_sync_date = false;
    if( !($launch_sync_str = $this->seconds_to_launch_sync_str()) )
        $launch_sync_str = false;

    if( empty( $all_methods ) )
    {
        ?>
        <div style="text-align: center">
            <?php echo $this->__( 'No payment methods defined in database for <strong>%s</strong> environment.', $environment )?><br/>
            <?php echo $this->__( 'In order to update payment methods, please select desired environment from Environment drop-down option and then save settings.' )?><br/>
            <br/>
            <?php echo $this->__( 'Last syncronization' )?>: <?php echo (empty( $last_sync_date )?'Never':$last_sync_date)?><br/>
            <button type="submit" value="<?php echo $this->__( 'Syncronize Now' )?>" title="<?php echo $this->__( 'Syncronize Now' )?>" name="s2p_submit_syncronize_methods" id="s2p_submit_syncronize_methods" class="scalable save"><span><span>Syncronize Now</span></span></button><br/>
            <br/>
            <small>Using Smart2Pay SDK version: <?php echo $this->get_sdk_version()?>.</small>
        </div>
        <?php
    } else
    {
?>
<div style="text-align: center">
    <?php echo $this->__( 'Displaying payment methods for <strong>%s</strong> environment.', $environment )?><br/>
    <?php echo $this->__( 'In order to update payment methods for other environments please select desired environment from Environment drop-down option and then save settings.' )?><br/>
    <br/>
    <?php echo $this->__( 'Last syncronization' )?>: <?php echo (empty( $last_sync_date )?$this->__( 'Never' ):$last_sync_date)?><br/>
    <?php
    if( empty( $launch_sync_str ) )
    {
        ?>
        <button type="submit" value="<?php echo $this->__( 'Syncronize Now' )?>" title="<?php echo $this->__( 'Syncronize Now' )?>" name="s2p_submit_syncronize_methods" id="s2p_submit_syncronize_methods" class="scalable save"><span><span>Syncronize Now</span></span></button>
        <?php
    } else
    {
        ?><?php echo $this->__( 'Time untill syncronization is available' )?>: <?php echo $launch_sync_str?>.<?php
    }
    ?><br/>
    <small>Using Smart2Pay SDK version: <?php echo $this->get_sdk_version()?>.</small>
    <br/>
</div>

<table id="s2p_methods_table">
<thead>
<tr>
    <th style="width: 30px;">#</th>
    <th style="width: 60px;"><?php echo $this->__( 'Enabled?' )?></th>
    <th style="width: 90px;"><?php echo $this->__( 'Surcharge' )?></th>
    <th colspan="2"><?php echo $this->__( 'Method' )?></th>
</tr>
</thead>
<tbody>
<tr>
    <td colspan="5">
        <p>
            <a href="javascript:void(0);" onclick="s2p_config_js_select_all()"><?php echo $this->__( 'Select all' )?></a>
            |
            <a href="javascript:void(0);" onclick="s2p_config_js_invert()"><?php echo $this->__( 'Invert' )?></a>
            |
            <a href="javascript:void(0);" onclick="s2p_config_js_deselect_all()"><?php echo $this->__( 'Select none' )?></a>
        </p>

    </td>
</tr>
<?php
$knti = 1;
$disabled_attributes = 'readonly="true"';

foreach( $all_methods as $method_arr )
{
    if( empty( $method_arr['countries_list'] )
     or !is_array( $method_arr['countries_list'] ) )
        $method_arr['countries_list'] = array();

    ?>
    <tr class="s2p-method-tr">
        <td class="sp2-middle-all"><?php echo $knti?></td>
        <td class="sp2-middle-all">
            <input type="checkbox"
                   id="s2p_enabled_method_<?php echo $method_arr['method_id']?>"
                   name="s2p_enabled_methods[]"
                   onchange="check_method_change( '<?php echo $method_arr['method_id']?>' )"
                   value="<?php echo $method_arr['method_id']?>"
                   <?php echo (!empty( $all_configured_methods[$method_arr['method_id']][0] )?'checked="checked"':'')?>
            /></td>
        <td class="sp2-middle-all" style="text-align: left;">
            <div style="padding:2px; clear:both;">
                <input type="text" class="input-text" style="width: 50px !important; text-align: right;"
                       name="s2p_surcharge[<?php echo $method_arr['method_id']?>]"
                       id="s2p_surcharge_<?php echo $method_arr['method_id']?>"
                       value="<?php echo ((!empty( $all_configured_methods[$method_arr['method_id']][0] ) and !empty( $all_configured_methods[$method_arr['method_id']][0]['surcharge'] ))?$all_configured_methods[$method_arr['method_id']][0]['surcharge']:0)?>"
                />%</div>
            <div style="padding:2px; clear:both;">
                <input type="text" class="input-text" style="width: 50px !important; text-align: right;"
                       name="s2p_fixed_amount[<?php echo $method_arr['method_id']?>]"
                       id="s2p_fixed_amount<?php echo $method_arr['method_id']?>"
                       value="<?php echo ((!empty( $all_configured_methods[$method_arr['method_id']][0] ) and !empty( $all_configured_methods[$method_arr['method_id']][0]['fixed_amount'] ))?$all_configured_methods[$method_arr['method_id']][0]['fixed_amount']:0)?>" />
                <?php echo $this->base_currency?></div>
        </td>
        <td class="sp2-middle-all s2p-method-img-td"><img class="s2p-method-img" alt="<?php echo $this->__( $method_arr['display_name'] ); ?>" src='<?php echo $method_arr['logo_url']?>' /></td>
        <td>
            <label for="s2p_enabled_method<?php echo $method_arr['method_id']?>"><strong><?php echo $this->__( $method_arr['display_name'] ); ?></strong></label>
            <br/>
            <?php echo $this->__( $method_arr['description'] ); ?><br/>
            <div id="s2p_meth_countries_<?php echo $method_arr['method_id']?>" style="height: 40px; overflow: hidden; text-overflow: ellipsis; display:block;">
            <strong><?php echo $this->__( 'Available in following countries' )?></strong>:
                (<a href="javascript:void(0);" style="text-decoration: underline;" onclick="show_all_countries_for_method( '<?php echo $method_arr['method_id']?>' )"><?php echo $this->__( 'toggle' )?></a>)
            <?php
            if( empty( $method_arr['countries_list'] ) )
                echo 'N/A';

            else
            {
                $first = true;
                foreach( $method_arr['countries_list'] as $country_id => $country_arr )
                {
                    if( !$first )
                        echo ', ';

                    echo $country_arr['name'];
                    $first = false;

                }
                echo '.';
            }
            ?>
            </div>
            <?php
            // Custom settings per country...
            if( !empty( $method_arr['countries_list'] )
            and count( $method_arr['countries_list'] ) > 1 )
            {
                $countries_per_line = 2;
                $has_3d_secure = false;
                if( $payment_model->has_3d_secure( $method_arr['method_id'] ) )
                    $has_3d_secure = true;
                ?>
                <div style="clear: both"></div>
                <div>
                &laquo; <a href="javascript:void(0);" style="text-decoration: underline;" onclick="show_all_country_custom_settings( '<?php echo $method_arr['method_id']?>' )"><?php echo $this->__( 'Per country settings' )?></a> &raquo;
                </div>
                <div id="s2p_meth_countries_settings_<?php echo $method_arr['method_id']?>" style="width:100%;display:none;">
                <p><?php echo $this->__( 'You can setup custom settings or disable method for specific countries. Use these settings only if you want to customize a specific country.' )?></p>
                <div>
                    <a href="javascript:void(0);" style="text-decoration: underline;" onclick="toggle_country_custom_settings_disabled( '<?php echo $method_arr['method_id']?>', 'checked' )">Disable All</a>
                    <a href="javascript:void(0);" style="text-decoration: underline;" onclick="toggle_country_custom_settings_disabled( '<?php echo $method_arr['method_id']?>', 'unchecked' )">Disable None</a>
                    <?php
                    if( $has_3d_secure )
                    {
                    ?>
                    |
                    <a href="javascript:void(0);" style="text-decoration: underline;" onclick="toggle_country_custom_settings_3dsecure( '<?php echo $method_arr['method_id']?>', 'yes' )">3DSecure All (Yes)</a>
                    <a href="javascript:void(0);" style="text-decoration: underline;" onclick="toggle_country_custom_settings_3dsecure( '<?php echo $method_arr['method_id']?>', 'no' )">3DSecure None (No)</a>
                    <a href="javascript:void(0);" style="text-decoration: underline;" onclick="toggle_country_custom_settings_3dsecure( '<?php echo $method_arr['method_id']?>', 'default' )">3DSecure Default</a>
                    <?php
                    }
                    ?>
                </div>
                <table style="width:100%" class="s2p_methods_custom_settings">
                <thead>
                <tr>
                    <?php
                    for( $ii = 0; $ii < $countries_per_line; $ii++ )
                    {
                        ?>
                        <th style="width:20px;"><span title="<?php echo $this->__( 'Customize method for this country' )?>" style="text-decoration: underline;">C</span></th>
                        <th style="width:20px;"><span title="<?php echo $this->__( 'Disable method for this country' )?>" style="text-decoration: underline;">D</span></th>
                        <th><?php echo $this->__( 'Country' )?></th>
                        <th style="width: 90px;"><?php echo $this->__( 'Surcharge' )?></th>
                        <?php
                        if( $has_3d_secure )
                        {
                            ?><th><?php echo $this->__( '3DSecure' )?></th><?php
                        }
                    }
                    ?>
                </tr>
                </thead>
                <?php
                $country_i = 0;
                foreach( $method_arr['countries_list'] as $country_id => $country_arr )
                {
                    $country_is_custom = false;
                    $country_disabled = false;
                    if( !empty( $all_configured_methods[$method_arr['method_id']][$country_id] )
                    and is_array( $all_configured_methods[$method_arr['method_id']][$country_id] ) )
                    {
                        $country_is_custom = true;
                        if( !empty( $all_configured_methods[$method_arr['method_id']][$country_id]['disabled'] ) )
                            $country_disabled = true;
                    }

                    if( $country_i == 0 )
                    {
                        ?><tr><?php
                    }

                    ?>
                    <td class="sp2-middle-all">
                        <input type="checkbox"
                               class="s2p_per_country_custom_field"
                               name="s2p_per_country[<?php echo $method_arr['method_id']?>][<?php echo $country_id?>][is_custom]"
                               id="s2p_per_country_<?php echo $method_arr['method_id']?>_<?php echo $country_id?>_is_custom"
                               value="1"
                               onchange="toggle_country_customization_for_method_and_country( '<?php echo $method_arr['method_id']?>', '<?php echo $country_id?>', 'update' )"
                               <?php echo ($country_is_custom?'checked="checked"':'')?>
                        /></td>
                    <td class="sp2-middle-all">
                        <input type="checkbox"
                               name="s2p_per_country[<?php echo $method_arr['method_id']?>][<?php echo $country_id?>][disabled]"
                               id="s2p_per_country_<?php echo $method_arr['method_id']?>_<?php echo $country_id?>_disabled"
                               value="1"
                               onchange="toggle_country_customization_for_method_and_country( '<?php echo $method_arr['method_id']?>', '<?php echo $country_id?>', 'update' )"
                               <?php echo ($country_disabled?'checked="checked"':'')?>
                        /></td>
                    <td class="sp2-middle-all"><?php echo $country_arr['name']?></td>
                    <td class="sp2-middle-all <?php echo (!$has_3d_secure?'s2p_methods_last_cell':'')?>" style="text-align: left;">
                        <div style="padding:2px; clear:both;">
                            <input type="text" class="input-text" style="width: 50px !important; text-align: right;"
                                   name="s2p_per_country[<?php echo $method_arr['method_id']?>][<?php echo $country_id?>][surcharge]"
                                   id="s2p_per_country_<?php echo $method_arr['method_id']?>_<?php echo $country_id?>_surcharge"
                                   value="<?php echo ((!empty( $all_configured_methods[$method_arr['method_id']][$country_id] ) and !empty( $all_configured_methods[$method_arr['method_id']][$country_id]['surcharge'] ))?$all_configured_methods[$method_arr['method_id']][$country_id]['surcharge']:0)?>"
                            />%</div>
                        <div style="padding:2px; clear:both;">
                            <input type="text" class="input-text" style="width: 50px !important; text-align: right;"
                                   name="s2p_per_country[<?php echo $method_arr['method_id']?>][<?php echo $country_id?>][fixed_amount]"
                                   id="s2p_per_country_<?php echo $method_arr['method_id']?>_<?php echo $country_id?>_fixed_amount"
                                   value="<?php echo ((!empty( $all_configured_methods[$method_arr['method_id']][$country_id] ) and !empty( $all_configured_methods[$method_arr['method_id']][$country_id]['fixed_amount'] ))?$all_configured_methods[$method_arr['method_id']][$country_id]['fixed_amount']:0)?>"
                            /> <?php echo $this->base_currency?></div>
                    </td>
                    <?php
                    if( $has_3d_secure )
                    {
                        if( !$country_is_custom
                         or !isset( $all_configured_methods[$method_arr['method_id']][$country_id]['3dsecure'] )
                         or !in_array( $all_configured_methods[$method_arr['method_id']][$country_id]['3dsecure'], array( 0, 1 ) ) )
                            $tdsecure_val = -1;

                        else
                            $tdsecure_val = intval( $all_configured_methods[$method_arr['method_id']][$country_id]['3dsecure'] );

                        ?>
                        <td class="sp2-middle-all s2p_methods_last_cell">
                            <select name="s2p_per_country[<?php echo $method_arr['method_id']?>][<?php echo $country_id?>][3dsecure]"
                                   id="s2p_per_country_<?php echo $method_arr['method_id']?>_<?php echo $country_id?>_3dsecure"
                            >
                            <option value="-1" <?php echo ($tdsecure_val==-1?'selected="selected"':'')?>><?php echo $this->__( 'Default' )?></option>
                            <option value="1" <?php echo ($tdsecure_val==1?'selected="selected"':'')?>><?php echo $this->__( 'Yes' )?></option>
                            <option value="0" <?php echo ($tdsecure_val==0?'selected="selected"':'')?>><?php echo $this->__( 'No' )?></option>
                        </select></td>
                        <?php
                    }

                    if( false && !$country_is_custom )
                    {
                        ?>
                        <script type="text/javascript">
                            toggle_country_customization_for_method_and_country( '<?php echo $method_arr['method_id']?>', '<?php echo $country_id?>', 'update' );
                        </script>
                        <?php
                    }

                    $country_i++;
                    if( $country_i == $countries_per_line )
                    {
                        ?></tr><?php
                        $country_i = 0;
                    }
                }
                ?>
                </table>
                </div>
                <?php
                if( true )
                {
                ?>
                <script type="text/javascript">
                toggle_country_customization_for_method( '<?php echo $method_arr['method_id']?>', 'update' );
                </script>
                <?php
                }
            }
            ?>
        </td>
    </tr>
    <?php
    $knti++;
}
?>
</tbody>
</table>
<?php
    }
